version: '3'
services:
  payment-service-nest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - mynetwork
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
