apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-payment
  labels:
    app: tech-challenge-payment
spec:
  template:
    metadata:
      name: tech-challenge-payment
      labels:
        app: tech-challenge-payment
    spec:
      containers:
        - name: tech-challenge-payment-api
          image: 637423603914.dkr.ecr.us-east-1.amazonaws.com/payment-service:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 40
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          env:
            - name: DATABASE_URL
              secretKeyRef:
                name: tech-challenge-secret
                key: DATABASE_URL
            - name: MERCADO_PAGO_URL
              secretKeyRef:
                name: tech-challenge-secret
                key: MERCADO_PAGO_URL
            - name: MERCADO_PAGO_TOKEN
              secretKeyRef:
                name: tech-challenge-secret
                key: MERCADO_PAGO_TOKEN
            - name: WEBHOOK_MP_URL
              secretKeyRef:
                name: tech-challenge-secret
                key: WEBHOOK_MP_URL
  replicas: 3
  selector:
    matchLabels:
      app: tech-challenge-payment