apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-payment-service
spec:
  type: LoadBalancer
  selector:
    app: tech-challenge-payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001